### ISSUE TITLE
Creates view that uses --attribute option 

### ISSUE THREAD

**Issue by BarthV** [3ofcoins/chef-browser#55]
Something I like with `knife search` is `-a` option.
I personally make a intensive use of it, like this trivial example : 

``` bash
> knife search node 'name:my-server-*' -a memory.total -a memory.swap.total
4 items found

my-server-04:
  memory.swap.total: 8388600kB
  memory.total:      8178868kB

my-server-01:
  memory.swap.total: 0kB
  memory.total:      33000552kB

my-server-03:
  memory.swap.total: 24012792kB
  memory.total:      16417888kB

my-server-02:
  memory.swap.total: 0kB
  memory.total:      32945692kB
```

Is It possible to create a search view in Chef-Browser for every node returned by the search but with multiple columns (1 for each attribute returned) 

Something like this :
**QUERY :**
- search : 'name:my-server-*'
- attributes : ['memory.total', 'memory.swap.total']

**RESULT :**

| node | memory.swap.total | memory.total |
| --- | --- | --- |
| my-server-01 | 0kB | 33000552kB |
| my-server-02 | 0kB | 32945692kB |
| my-server-03 | 24012792kB | 16417888kB |
| my-server-04 | 8388600kB | 8178868kB |

**Comment by xamebax** [comment]
Hey, thanks for the suggestion! It's an interesting idea. Chef Browser interacts with the server using [Ridley](https://github.com/reset/ridley/), so we're somehow limited by what Ridley can do. I had a look around its code and if I understand correctly, Ridley doesn't support attributes [in its searches at this point](https://github.com/reset/ridley/blob/master/lib/ridley/resources/search_resource.rb). Or maybe I'm missing something obvious.

**Comment by BarthV** [comment]
Ok
I have opened an issue in Ridley, with -not that much- hope :-)

**Comment by xamebax** [comment]
Closing for the time being.
