### ISSUE TITLE
run command should be changed

### ISSUE THREAD

**Issue by donnielee** [3ofcoins/chef-browser#64]
When I used 'rackup config.ru' for running chef-browser, I could not access it remotely using curl although curl command worked locally. But I used 'puma -e production' command following below url, I could access chef-browser remotely. 

https://3ofcoins.net/2013/12/11/we-released-chef-browser-today/

So I would prefer run command be changed to 'puma -e production' from 'rackup config.ru.'

**Comment by xamebax** [comment]
Thanks for opening the issue, good catch. You can use the `-o` flag with `rackup` and pass `0.0.0.0` if you want Chef Browser to be accessible to other machines (`rackup -o 0.0.0.0 config.ru`). I'll update the README.
